apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Brian Monroe <paradoxguitarist@fedoraproject.org>
    commit.image.appsody.dev/committer: Brian Monroe <paradoxguitarist@fedoraproject.org>
    commit.image.appsody.dev/date: Tue Jun 9 10:30:05 2020 -0700
    commit.image.appsody.dev/message: Use axios instead of request, because request
      is deprecated
    commit.stack.appsody.dev/author: Enrique Lacal <Enrique.Lacal.Bereslawski@ibm.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/nodejs-express
    commit.stack.appsody.dev/date: Thu Jun 4 10:47:57 2020 +0100
    commit.stack.appsody.dev/message: 'nodejs-express: define APPSODY_DEBUG_PORT (#820)'
    image.opencontainers.org/created: "2020-06-09T11:04:58-07:00"
    image.opencontainers.org/documentation: https://github.com/SWheeler17/bitbucket-quay-connector
    image.opencontainers.org/revision: 93a3135bcefff1c1fe10d010788d6fa600a643c2-modified
    image.opencontainers.org/source: https://github.com/SWheeler17/bitbucket-quay-connector/tree/master
    image.opencontainers.org/url: https://github.com/SWheeler17/bitbucket-quay-connector
    stack.appsody.dev/authors: Sam Roberts <sam-github>
    stack.appsody.dev/configured: docker.io/appsody/nodejs-express:0.4
    stack.appsody.dev/created: "2020-06-04T09:50:35Z"
    stack.appsody.dev/description: Express web framework for Node.js
    stack.appsody.dev/digest: sha256:f45f2557cfbef99ba898e8aa2412515f264a9feff27ab81f20dd44389aeff7c6
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/nodejs-express/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: d4c368144c333187df99e93069c9b517e3ede413
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/nodejs-express/image
    stack.appsody.dev/tag: docker.io/appsody/nodejs-express:0.4.10
    stack.appsody.dev/title: Node.js Express
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/nodejs-express
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: bitbucket-quay-connector
    stack.appsody.dev/id: nodejs-express
    stack.appsody.dev/version: 0.4.10
  name: bitbucket-quay-connector
spec:
  applicationImage: bitbucket-quay-connector
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: bitbucket-quay-connector
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 3000
    type: NodePort
  stack: nodejs-express
  version: 1.0.0
